### ISSUE TITLE
Mines Tool does nothing

### ISSUE THREAD

**Issue by ignBiometrical** [Ale1x/X-Prison-Patched#2]
I have recently setup X-Prison Patched, and attempted to use the mines tool, but have received quite literally nothing. There are no messages, no errors, just me trying to click a stick and receiving nothing. Any help is appreciated.

**Comment by ignBiometrical** [comment]
Using the below code, when clicking, it still provides 0 info. I believe it is not being triggered. I am running on default Paper 1.20.6

```java
private void subscribeToPlayerInteractEvent() {
		Events.subscribe(PlayerInteractEvent.class)
				.filter(e -> e.getItem() != null && e.getItem().isSimilar(MineManager.SELECTION_TOOL) && e.getClickedBlock() != null)
				.handler(e -> {
					System.out.println("You have clicked a block");
					int pos = e.getAction() == Action.LEFT_CLICK_BLOCK ? 1 : e.getAction() == Action.RIGHT_CLICK_BLOCK ? 2 : -1;

					if (pos == -1) {
						return;
					}

					e.setCancelled(true);

					this.plugin.getManager().selectPosition(e.getPlayer(), pos, Position.of(e.getClickedBlock()));
				}).bindWith(this.plugin.getCore());
	}
```

**Comment by Ale1x** [comment]
Hello! No error on 1.21.
Could you share with me your plugins list and server version (build number)
@ignBiometrical
